# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Openly licensed images of manuscripts
tagline:          'Sources for openly licensed images of manuscripts'
description:      'Sources for openly licensed images of manuscripts'

baseurl: '/img_sources/'


author:
  name:           'Neel Smith'
 

paginate:         5

github:
  repo:           https://github.com/openpaleography/img_sources

links:
  - title: Open Paleography
    url: http://openpaleography.github.io
    external: true
  - title: Github project
    url: https://github.com/openpaleography/img_sources
    external: true
